# Generated by Django 3.2.4 on 2022-01-02 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(max_length=170)),
                ('activation', models.BooleanField(blank=True, default=False, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Category_by', to='dashboard.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user', to='account.profile')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to='account.Profile')),
                ('sections', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sections_by', to='dashboard.sections')),
            ],
        ),
    ]
