# Generated by Django 3.2.4 on 2021-12-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
