# Generated by Django 3.2.4 on 2022-01-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='data_type',
            field=models.CharField(blank=True, choices=[('POST', 'POST'), ('GROUP', 'GROUP')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='link',
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
    ]
