# Generated by Django 3.2.4 on 2021-07-19 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groub',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Category_name', to='whatsApp.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groub',
            name='sections',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Sections_name', to='whatsApp.sections'),
            preserve_default=False,
        ),
    ]
