# Generated by Django 3.2.4 on 2021-07-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsApp', '0002_groub_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='groub',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'واتساب'), ('2', 'تليجرام'), ('3', 'انستقرام'), ('4', 'يوتيوب'), ('5', 'تطبيق'), ('6', 'غير معروف')], default='1', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='groub',
            name='sections',
            field=models.CharField(blank=True, choices=[('1', 'الكل'), ('2', 'إسلامية'), ('3', 'أنمي'), ('4', 'ترفيه'), ('5', 'تعارف'), ('6', 'وظائف'), ('7', 'سياسة'), ('8', 'تعليم'), ('9', 'نكت'), ('10', 'اعلانات'), ('11', 'منوع'), ('12', 'دعم')], default='1', max_length=2, null=True),
        ),
    ]
