# Generated by Django 3.2.4 on 2021-07-17 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsApp', '0006_auto_20210717_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groub',
            name='category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Category_name', to='whatsApp.category'),
        ),
        migrations.AlterField(
            model_name='groub',
            name='sections',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sections_name', to='whatsApp.sections'),
        ),
    ]
